<?php

namespace Pterodactyl\BlueprintFramework\Doctor\Checks;

use Pterodactyl\BlueprintFramework\Doctor\CheckInterface;
use Pterodactyl\BlueprintFramework\Doctor\CheckResult;
use Pterodactyl\BlueprintFramework\Doctor\Issue;
use Pterodactyl\BlueprintFramework\Doctor\Severity;

class ConfigurationCheck implements CheckInterface
{
    public function name(): string { return 'configuration'; }
    public function title(): string { return 'Configuration'; }

    public function run(): CheckResult
    {
        $r = new CheckResult($this->name(), $this->title());

        $env = base_path('.env');
        if (file_exists($env)) {
            $r->ok('.env', 'Present');
        } else {
            $r->err('.env', 'Missing');
            $r->issue(new Issue(
                Severity::CRITICAL,
                '.env file missing',
                'The Pterodactyl environment file is missing.',
                'Restore .env from .env.example.',
            ));
        }

        $key = config('app.key');
        if ($key && $key !== 'base64:') {
            $r->ok('APP_KEY', 'Set');
        } else {
            $r->err('APP_KEY', 'Not set');
            $r->issue(new Issue(
                Severity::CRITICAL,
                'APP_KEY not set',
                'Pterodactyl cannot encrypt sessions.',
                'Run: php artisan key:generate',
            ));
        }

        $url = config('app.url');
        if ($url) {
            $r->ok('APP_URL', (string) $url);
        } else {
            $r->warn('APP_URL', 'Not set');
            $r->issue(new Issue(
                Severity::WARNING,
                'APP_URL not set',
                'URLs generated by Blueprint may be wrong.',
                'Set APP_URL in .env.',
            ));
        }

        return $r;
    }
}